### Test root endpoint
GET http://localhost:7071/api/hotels/

###

### Create hotel
POST http://localhost:7071/api/hotels/hotel
Content-Type: application/json

[
  {"id": 8, "name": "Hotel 8", "address": "Address 8"},
  {"id": 9, "name": "Hotel 9", "address": "Address 9"}
]

###

### Get all hotels
GET http://localhost:7071/api/hotels/hotel

###

### Get hotel by id
GET http://localhost:7071/api/hotels/hotel/1

###

### delete hotel by id
DELETE http://localhost:7071/api/hotels/hotel/3

###

### delete hotel by id
GET http://localhost:7071/api/hotels/hotel/3

###

### delete room by id
DELETE http://localhost:7071/api/hotels/room/2

###

### get room by id
GET http://localhost:7071/api/hotels/room/2

###

### get all rooms for hotel
GET  http://localhost:7071/api/hotels/room/1/rooms

###

### Security
POST http://localhost:7071/api/hotels/auth/login
Content-Type: application/json

{
    "username": "user2",
    "password": "pass124"
}


###

GET http://{{url}}/api/hotels/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoidXNlcjIiLCJleHAiOjE3NTk0MzE2MDcsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjIifQ.ACYeyUA1HARjVYcrsWBPB6Sape1ZH1D7837pZwevxoY
